#BSUB -L /bin/bash              
#BSUB -J admix
#BSUB -n 1
#BSUB -R "span[ptile=1]" 
#BSUB -R "rusage[mem=5000]"
#BSUB -M 5000
#BSUB -W 24:00
#BSUB -o stdout.%J
#BSUB -e stderr.%J 
#BSUB -u edegreef@ucdavis.edu
#BSUB -B -N

#note, the bim and fam files in the input files are edited for chrom and popinfo

cd /scratch/user/edegreef/reseq/admixture
module load ADMIXTURE/1.3.0
admixture 67_auto.bed 1
admixture 67_auto.bed 2
admixture 67_auto.bed 3
admixture 67_auto.bed 4
